### ISSUE TITLE
currentView不起作用

### ISSUE THREAD

**Issue by foolishandi** [P4X666/custom-calendar-taro#17]
<Calendar
        hideArrow
        ref={calendarRef}
        marks={calendarData.markerList}
        selectedDate={calendarData.selectDay}
        currentView={calendarData.currentView}
        view={calendarData.mode as any}
        custDayRender={custDayRender}
        custWeekRender={custWeekRender}
        onDayClick={(_item, date) => {
         }
      />
    </div>
大佬这里的currentView并不能切换到对应的月视图，selectDate也不能自动跳到对应的包含对应日期的视图，这个是代码有什么问题吗

**Comment by P4X666** [comment]
因为你传入了custDayRender，也就是自定义渲染日期，组件就默认你是自定义渲染，一切渲染由你来控制，你可以打印一下custDayRender的传参

**Comment by P4X666** [comment]
`js
<CustCalendar
        view={type}
        ref={custCalendarInstance}
        currentView='2024-03-16'
        selectedDate='2024-03-16'
        marks={[
          { value: '2022-09-21', color: 'red' },
          { value: '2022-09-22', color: 'pink' },
          { value: '2022-09-23', color: 'gray' },
          { value: '2022-09-24', color: 'yellow' },
          { value: '2022-09-25', color: 'darkblue' },
          { value: '2022-09-26', color: 'pink' },
          { value: '2022-09-27', color: 'green' }
        ]}
        extraInfo={[
          { value: '2022-09-25', text: '生日', color: 'red' },
          { value: '2022-09-26', text: '休假', color: 'darkblue' },
          { value: '2022-09-27', text: '会议', color: 'gray' }
        ]}
        custDayRender={custDayRender}
        custWeekRender={custWeekRender}
      />
`

**Comment by P4X666** [comment]
```js
<CustCalendar
        view={type}
        ref={custCalendarInstance}
        currentView='2024-03-16'
        selectedDate='2024-03-16'
        marks={[
          { value: '2022-09-21', color: 'red' },
          { value: '2022-09-22', color: 'pink' },
          { value: '2022-09-23', color: 'gray' },
          { value: '2022-09-24', color: 'yellow' },
          { value: '2022-09-25', color: 'darkblue' },
          { value: '2022-09-26', color: 'pink' },
          { value: '2022-09-27', color: 'green' }
        ]}
        extraInfo={[
          { value: '2022-09-25', text: '生日', color: 'red' },
          { value: '2022-09-26', text: '休假', color: 'darkblue' },
          { value: '2022-09-27', text: '会议', color: 'gray' }
        ]}
        custDayRender={custDayRender}
        custWeekRender={custWeekRender}
      />
```

**Comment by P4X666** [comment]
```js
const custWeekRender = (weekItem: string) => {
    return (
      <View style={['六', '日'].includes(weekItem) ? { color: 'red' } : {}}>
        {weekItem}
      </View>
    );
  };
  const custDayRender = (dayProps: DayProps) => {
    const isRest = [6, 0].includes(dayProps.weekDay);
    return (
      <>
        <View style={isRest ? { color: 'red' } : {}}>{dayProps.day}</View>
        {isRest && <View className={styles.tips}>休息</View>}
      </>
    );
  };
```

**Comment by P4X666** [comment]
```js
const custWeekRender = (weekItem: string) => {
    return (
      <View style={['六', '日'].includes(weekItem) ? { color: 'red' } : {}}>
        {weekItem}
      </View>
    );
  };
const custDayRender = (dayProps: DayProps) => {
    const isRest = [6, 0].includes(dayProps.weekDay);
    return (
      <>
        <View style={isRest ? { color: 'red' } : {}}>{dayProps.day}</View>
        {isRest && <View className={styles.tips}>休息</View>}
      </>
    );
  };
```
