### ISSUE TITLE
通过接口获取数据后如何让日历刷新

### ISSUE THREAD

**Issue by zanyfly** [P4X666/custom-calendar-taro#19]
发现获取完数据后 没有办法能让custDayRender进行调用

**Comment by zzy-33** [comment]
> 发现获取完数据后 没有办法能让custDayRender进行调用

你找到解决问题了吗？？？

**Comment by P4X666** [comment]
pages里面有示例啊，你看一下custRender呢`
`
const custDayRender = (dayProps: DayProps) => {
    const isRest = [6, 0].includes(dayProps.weekDay);
    return (
      <>
        <View style={isRest ? { color: 'red' } : {}}>{dayProps.day}</View>
        {isRest && <View className={styles.tips}>休息</View>}
      </>
    );
  };

**Comment by P4X666** [comment]
或者你们想要的是修改`currentView` 吗？

**Comment by zzy-33** [comment]
我试了一下，通过hook去动态改变选中状态，好像不太行？它还是默认是一开始选中的时间，可以看下下面的样例
```
  const [currentDate, setCurrentDate] = useState<string>("2024-11-01")

return (
<View>
   <View onClick={()=>setCurrentDate("2024-10-01")}>改变</View>
    <Calendar
        marks={markList}
        view="week"
        selectedDate={currentDate}
        currentView={currentDate}
        startWeekDay={0}
        hideController
      />
</View>
)
```

**Comment by P4X666** [comment]
了解了，我更新了一版，现在就可以了

**Comment by zzy-33** [comment]
> 了解了，我更新了一版，现在就可以了

可以了，牛掰，麻烦看下我的pull requests谢谢🙏
