### ISSUE TITLE
大小写拼写错误

### ISSUE THREAD

**Issue by Rlagnl** [P4X666/custom-calendar-taro#3]
npm 上的 1.0.10 版本与当前main分支内容不符。

1.0.10 版本中 ./index.ts 文件中的 CustomCalendar 引入路径为 './src/components/Calendar'，但实际该文件路径为 ./src/components/calendar，导致 linux 环境中无法正常编译。

烦请统一

**Comment by P4X666** [comment]
多谢提醒！现已更新。
