### ISSUE TITLE
taro 3.3.7版本, 日历切换月份 无效

### ISSUE THREAD

**Issue by houhoz** [P4X666/custom-calendar-taro#4]
![Kapture 2021-09-08 at 22 03 31](https://user-images.githubusercontent.com/19684376/132524733-b48195f5-3774-4fdb-9f05-e5aec809f8e1.gif)

**Comment by P4X666** [comment]
我看官方的Swiper在h5端是有问题的，要不你试着降级到3.2.x呢，我这个在3.0-3.2是没发现有啥问题的

**Comment by houhoz** [comment]
我试着降级3.0.0 还是一样的问题。。
![image](https://user-images.githubusercontent.com/19684376/132641064-663dda80-4851-47d2-87d2-c0e7fd28665d.png)  
点击下一个月份 current应该是10月份，之后打印出来还是9月份
可以给我一点思路 我去研究一下

**Comment by P4X666** [comment]
你在外界是不是控制着currentView或者selectedDate？这两个是抛出去，方便控制日历显示的。我从你给的图片中没发现有啥问题，上面显示的确实是10月份啊

**Comment by houhoz** [comment]
外面没控制的，代码只是修改了marks日期，
`import React, { FunctionComponent, useRef, useState } from 'react'
import { View, Button } from '@tarojs/components'
import CustomCalendar from '../../components/Calendar'
import './index.scss'

const Index: FunctionComponent = () => {

  const [type, setType] = useState<'week' | 'month'>('week')
  // 组件节点
  const CalendarComponent: any = useRef(null);
  // 修改视图类型
  const viewHandle = () => {
    setType(type === 'week' ? 'month' : 'week')
  }
  // 设置当前的视图
  const setCurrentView = date => {
    console.log(date);
  }
  // 向前
  const goPre = () => {
    CalendarComponent.current.goPre()
  }
  // 向后
  const goNext = () => {
    CalendarComponent.current.goNext()
  }
  const customStyleGenerator = {
    extraInfoStyle: {
      position: 'absolute',
      fontSize: '0.5rem',
      right: '-0.8rem',
      top: '0'
    },
    dateStyle: {
      marginTop: '0.6rem',
      borderRadius: '30%'
    },
    markStyle: {
      top: 'auto',
      bottom: '0',
      right: '50%',
      transform: 'translateX(50%)'
    }
  };
  return (
    <View className='index'>
      <CustomCalendar
        view={type}
        marks={[
          { value: '2021-09-11', color: 'red', markSize: '9px' },
          { value: '2021-09-12', color: 'pink', markSize: '9px' },
          { value: '2021-09-13', color: 'gray', markSize: '9px' },
          { value: '2021-09-14', color: 'yellow', markSize: '9px' },
          { value: '2021-09-15', color: 'darkblue', markSize: '9px' },
          { value: '2021-09-16', color: 'pink', markSize: '9px' },
          { value: '2021-09-23', color: 'green', markSize: '9px' },
        ]}
        customStyleGenerator={() => customStyleGenerator}
        extraInfo={[
          { value: '2021-09-21', text: '生日', color: 'red' },
          { value: '2021-09-22', text: '休假', color: 'darkblue' },
          { value: '2021-09-23', text: '会议', color: 'gray' },
        ]}
        isMultiSelect
        selectedDateColor='#346fc2'
        onDayClick={item => console.log(item)}
        onDayLongPress={item => console.log(item)}
        onCurrentViewChange={setCurrentView}
      />
      <View>
        <Button onClick={viewHandle}>切换周和月</Button>
        <Button onClick={goPre}>上一页</Button>
        <Button onClick={goNext}>下一页</Button>
      </View>
    </View>
  )
}


export default Index;
`
第一个debug
![image](https://user-images.githubusercontent.com/19684376/132656464-ae21841b-7d65-4dc3-b887-4758740926be.png)

第二个debug

![image](https://user-images.githubusercontent.com/19684376/132656522-1cb798c4-a4f7-4f93-997f-22ec01756423.png)

**Comment by yangjie21** [comment]
![image](https://user-images.githubusercontent.com/19204745/133922257-663ba17b-9a23-40fb-9d5d-dfcd3fdecf8e.png)
这段代码有问题

**Comment by P4X666** [comment]
@yangjie21 确实是我方法调错了，多谢大佬提醒

**Comment by P4X666** [comment]
@houhoz 老哥，这个问题解决了，我就关闭了哦
